name: Run simple shell
on: [push]

jobs:

  linux_run:
    name: My first run
    runs-on: ubuntu-latest
    steps:
      - name: Basic Bash shell command
        env:
          MYNAME: John
        run: |
         date
         uname 
         echo $MYNAME
        shell: bash 
  
  windows_run:
    name: My second run
    runs-on: windows-latest
    steps:
      - name: Basic PowerShell commands 
        env: 
          MY_NAME: John Smith  
        run: |
           Get-Date
           Write-Output $env:MY_NAME
        shell: powershell 
